using System.Diagnostics.CodeAnalysis;

namespace MovescountBackup.Lib.Enums
{
    /// <summary>
    /// Movescount activity enum
    /// </summary>
    [SuppressMessage("ReSharper", "UnusedMember.Global")]
    public enum ActivityIdEnum
    {
        NotSpecifiedSport = 1,
        MultiSport = 2,
        Run = 3,
        Cycling = 4,
        MountainBiking = 5,
        Swimming = 6,
        Skating = 8,
        Aerobics = 9,
        YogaPilates = 10,
        Trekking = 11,
        Walking = 12,
        Sailing = 13,
        Kayaking = 14,
        Rowing = 15,
        Climbing = 16,
        IndoorCycling = 17,
        CircuitTraining = 18,
        Triathlon = 19,
        AlpineSkiing = 20,
        Snowboarding = 21,
        CrosscountrySkiing = 22,
        WeightTraining = 23,
        Basketball = 24,
        Soccer = 25,
        IceHockey = 26,
        Volleyball = 27,
        Football = 28,
        Softball = 29,
        Cheerleading = 30,
        Baseball = 31,
        Tennis = 33,
        Badminton = 34,
        TableTennis = 35,
        RacquetBall = 36,
        Squash = 37,
        CombatSport = 38,
        Boxing = 39,
        Floorball = 40,
        ScubaDiving = 51,
        FreeDiving = 52,
        AdventureRacing = 61,
        Bowling = 62,
        Cricket = 63,
        Crosstrainer = 64,
        Dancing = 65,
        Golf = 66,
        Gymnastics = 67,
        Handball = 68,
        HorsebackRiding = 69,
        IceSkating = 70,
        IndoorRowing = 71,
        Canoeing = 72,
        Motorsports = 73,
        Mountaineering = 74,
        Orienteering = 75,
        Rugby = 76,
        SkiTouring = 78,
        Stretching = 79,
        TelemarkSkiing = 80,
        TrackAndField = 81,
        TrailRunning = 82,
        OpenWaterSwimming = 83,
        NordicWalking = 84,
        SnowShoeing = 85,
        Surfing = 86,
        Kettlebell = 87,
        RollerSkiing = 88,
        StandupPaddling = 89,
        CrossFit = 90,
        Kiting = 91,
        Paragliding = 92,
        Treadmill = 93,
        Frisbee = 94,
        IndoorTraining = 95
    }
}
